app/discovery/routes.py
from app.discovery.forms import SearchForm
from app.discovery.models.data import get_fund_name
from app.discovery.models.data import list_data
from app.discovery.models.data import query_fund
from app.discovery.models.data import query_rounds
from app.discovery.models.rounds import Rounds
from config import Config
from flask import Blueprint
from flask import render_template
from flask import request

discovery_bp = Blueprint("discovery_bp", __name__, template_folder="templates")


@discovery_bp.route("/")
def search_funds():
    """GIVEN route takes a search form, retrieves
    user input/query & return query response
    from fund store.
    """

    form = SearchForm()
    query = request.args.get("search", "")

    query_response = query_fund(
        query, Config.FUNDS_SEARCH_URL.format(host=Config.FUND_STORE_API_HOST)
    )
    return render_template(
        "search.html",
        query=query,
        query_response=query_response,
        form=form,
    )


@discovery_bp.route("/round/<fund_id>", methods=["GET", "POST"])
def fund_rounds(fund_id):
    """
    GIVEN Function calls the RoundStore function
    from data model to check rounds with given endpoint
     & id.
     Function query_fund send QUERY to fund store
     so the fund name can be displayed onto the rounds page.
    """
    fund_rounds_data = query_rounds(
        Config.ROUNDS_URL.format(
            host=Config.FUND_STORE_API_HOST, fund_id=fund_id
        )
    )

    if fund_rounds_data:
        rounds = list_data(fund_rounds_data, Rounds.fund_rounds)
    else:
        error = "No rounds exist for this fund"
        return render_template("fund.html", error=error)

    fund = get_fund_name(
        Config.FUNDS_URL.format(
            host=Config.FUND_STORE_API_HOST, fund_id=fund_id
        )
    )

    return render_template(
        "fund.html",
        fund=fund,
        rounds=rounds,
        authenticator_magic_link_url=Config.AUTHENTICATOR_MAGIC_LINK_URL,
    )

app/discovery/templates/debug_continue.html
{%- from "govuk_frontend_jinja/components/input/macro.html" import govukInput -%}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}

{% extends "base.html" %}

{% block content %}

{% if account_exists == True%}
<h2 class="govuk-heading-m">This account exists! Here's the data: </h2>
<p class="govuk-body">{{account_data|string}}</p>

{% else %}
<h2 class="govuk-heading-m">This account has just been made:</h2>
<p class="govuk-body">{{account_data|string}}</p>
{% endif %}

{{ govukButton({
  "text": "Start application",
  "href": application_url,
  "isStartButton": true
}) }}

{% endblock %}

app/discovery/templates/email.html
{%- from "govuk_frontend_jinja/components/input/macro.html" import govukInput -%}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}

{% extends "base.html" %}

{% block content %}

<form method="POST">

{{ form.csrf_token }}

{{ govukInput({
  "label": {
    "text": "Email address"
  },
  "id": form.email.id,
  "name": form.email.id,
  "type": "email",
  "autocomplete": "email",
  "spellcheck": false,
}) }}

{{ govukButton({
  "text": "Continue",
  "preventDoubleClick": true,
}) }}

</form>

{% endblock %}

app/discovery/templates/fund.html
  {% extends "base.html" %}

{% from "govuk_frontend_jinja/components/input/macro.html" import govukInput %}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}

{% block content %}


  <div>
    {% if fund %}

    <h1 class="govuk-label-wrapper"> <label class="govuk-label govuk-label--l">
      {{fund['fund_name']|upper}} </label> </h1>

      {% else %}
        <h1 class="govuk-label-wrapper"> <label class="govuk-label govuk-label--m">
        {{error}} </label> </h1>
      {% endif %}
</div>


   {% for round in rounds %}
   <table class="govuk-table govuk-!-margin-top-9 role="banner">

    <caption class="govuk-table__caption govuk-table__caption--l">{{round.round_title|upper }}</caption>

    <thead class="govuk-table__head">
      <tr class="govuk-table__row">
        <th scope="col" class="govuk-table__header">Round title</th>
        <th scope="col" class="govuk-table__header">{{round.round_title|upper }}</th>
      </tr>
    </thead>

    <tbody class="govuk-table__body">
      <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header">Eligibility criteria</th>
        <td class="govuk-table__cell"> Maximum cost:
          £{{ round.eligibility_criteria_formatted }}
        </td>
      </tr>
      <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header">Start date</th>
        <td class="govuk-table__cell">{{round.opens_formatted}}</td>
      </tr>
      <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header">End date</th>
        <td class="govuk-table__cell">{{round.deadline_formatted}}</td>
      </tr>
    </tbody>
  </table>


  <a href="{{authenticator_magic_link_url.format(fund_id=fund['fund_id'],round_id=round['round_id'])}}" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button"> Start application <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false"> <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z"/> </svg></a>


 {% endfor %}

<div>
  <a href="{{url_for('discovery_bp.search_funds')}}" role="button" draggable="false" class="govuk-button govuk-button--secondary govuk-!-margin-top-8" data-module="govuk-button"> Back to search </a>
</div>

  {% endblock %}

app/discovery/templates/login_link.html
{%- from "govuk_frontend_jinja/components/input/macro.html" import govukInput -%}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}
{%- from "govuk_frontend_jinja/components/panel/macro.html" import govukPanel -%}

{% extends "base.html" %}

{% block content %}

{{ govukPanel({
  "titleText": "We've emailed you a link to sign in",
  "html": "Check your email and follow the link to continue your application"
}) }}

{% endblock %}

app/discovery/templates/magic_link.html
{%- from "govuk_frontend_jinja/components/input/macro.html" import govukInput -%}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}
{%- from "govuk_frontend_jinja/components/panel/macro.html" import govukPanel -%}

{% extends "base.html" %}

{% block content %}

{{ govukPanel({
  "titleText": "We've emailed you a link to sign in",
  "html": "Check your email and follow the link to continue your application"
}) }}

{% endblock %}

app/discovery/templates/search.html
{% extends "base.html" %}


{% from "govuk_frontend_jinja/components/input/macro.html" import govukInput %}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}

{% block content %}


<form method="GET" action="/">
  <div class="govuk-form-group">
    <h1 class="govuk-label-wrapper"><label class="govuk-label govuk-label--l" for="weight">
       Fund search
      </label>
    </h1>
    <div class="govuk-input__wrapper">
      <input class="govuk-input govuk-!-width-three-quarters"  type="text" spellcheck="false" id="{{form.search.id}}" name="{{form.search.id}}" value="{{request.args.get('search', '')}}" placeholder="search fund with keyword">

      <button type="submit" class="govuk-button govuk-button--secondary" data-module="govuk-button">
        Search
      </button>
    </div>
  </div>
</form>

<div class="govuk-grid-row">

  <div class="govuk-grid-column-one-third">

    <div>
    <h2 class="govuk-heading-m">Choose a category</h2>
    <ul class="govuk-list govuk-body-m govuk-!-margin-top-4">
    <li aria-current="page">
      <strong>All categories</strong>
      <ul class="govuk-list govuk-body-m">
        <li><a class="govuk-link"  href="#">Category one</a></li>
        <li><a class="govuk-link"  href="#">Category two</a></li>
        <li><a class="govuk-link"  href="#">Category three</a></li>
      </ul>
    </li>
    </ul>
  </div>

  <div class="govuk-!-margin-top-8">
    <h2 class="govuk-heading-m">Apply filters
      <span class="govuk-!-margin-left-9">  <a class="govuk-list govuk-body-s"  href="#"> Clear filters</a></span>
    </h2>
    <ul class="govuk-list">
      <li><a class="govuk-link" href="#">Filter one</a></li>
      <li><a class="govuk-link" href="#">Filter two</a></li>
      <li><a class="govuk-link" href="#">Filter three</a></li>
      <li><a class="govuk-link" href="#">More</a></li>
    </ul>
  </div>

  <div class="govuk-!-margin-top-8 govuk-body">
    <h2 class="govuk-heading-m">Information
    </h2>
    <p class="govuk-hint">Sed ut perspiciatis unde omnis istei natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
  </div>

  </div>


  <div class="govuk-grid-column-two-thirds govuk-body">
    <div class="govuk-body" >
      {% if query %}
      <span class="govuk-body govuk-!-font-size-48"><strong>{{query_response|length if query_response else 0}} </strong></span>
       results found containing <strong>{{query}}</strong> in <strong>All funds</strong>

       {% else %}
       <span class="govuk-body govuk-!-font-size-48"><strong>{{query_response|length if query_response else 0}} </strong></span>
       results found in <strong>All funds</strong>
       {% endif %}



  </div>
  {% if query_response %}
    {% for fund in query_response %}

    <div class="govuk-grid-row">
      <div class="govuk-grid-column-full">
          <h1 class="govuk-heading-s govuk-!-margin-top-1">
            <a class = 'govuk-link fund_name' href="{{url_for('discovery_bp.fund_rounds', fund_id=fund['fund_id']) }}"> {{fund['fund_name']}}</a>
          </h1>
        <p class="govuk-body">  {{fund['fund_description']}}.
          Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras mauris metus, maximus gravida finibus sed, sodales eget lectus. Nunc aliquam a libero ut rhoncus. Proin eu sapien quis nisl hendrerit dapibus sed sit amet dolor.
        </p>

      <hr class="govuk-section-break govuk-section-break--visible">
    {% endfor %}
    {% endif %}
  </div>

</div>
  {% endblock %}